name: Bash
version: '1.0-SNAPSHOT'
main: me.stoffeh.bash.Bash
description: Execute multiple commands from file!
api-version: '1.20'
commands:
  bash:
    description: Execute command from file with delay.
    usage: /bash <filename> <delay>
    permission: bash.use

